name: bluetooth_identifiers
description: Codification of Bluetooth specificiers for manufacturer & service data.
version: 1.0.4
repository: https://github.com/LEMUSADR000/bluetooth_identifiers
homepage: https://github.com/LEMUSADR000/bluetooth_identifiers
issue_tracker: https://github.com/LEMUSADR000/bluetooth_identifiers/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0