name: bluetooth_identifiers
description: Codification of Bluetooth specificiers for manufacturer & service data.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0